- topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

- service_name: "world/empty/set_pose"
  ros_type_name: "ros_gz_interfaces/srv/SetEntityPose"
  gz_req_type_name: "gz.msgs.Pose"
  gz_rep_type_name: "gz.msgs.Boolean"
